### PR TITLE
iscsid daemon

### PR DESCRIPTION
**Pull request by almumontiel**
let the daemon iscsid to start if the variable OS_CORE_ISCSI_ENABLED is set to true

### CODE REVIEW

**Comment by jouvin** [comment]
@almumontiel Nice catch... and I'm wondering if it is not the cause for a problem we observe on only one of our server mounting an iscsi volume in fstab as `iscsid`, started by `iscsi` if needed, may be stopped by `ncm-chkconfig`. Strictly speaking, there is no reason for `iscsid` to be started by `initd` (or `systemd`) and so it was reasonable to have it in the `UNWANTED_DAEMONS` list but the `startstop` property should not be set for it. But your suggested modification should work (just if it has been marked as on manually, it will not be reset until `OS_CORE_ISCSI_ENABLED` is false).

Any comment by others with iscsi experience?

Also not that the same fix must probably done for `sl6.x`.

**Comment by jouvin** [comment]
Bad day... I deleted my previous comment by mistake... If somebody has a copy of it (in the GitHub email), he can paste it again... The summary was that I think that the fix is ok and should address the problem (`ncm-chkconfig` potentially stopping `iscsid` previously started by `iscsi` daemon, the only one that needs to be enabled). In fact, `iscsid` should always not be configured for starting during boot (this is why the line removed is there) and it should be enough to remove the `startstop` property for this service but I think that this would increase the complexity of the template for no real benefit...

My other point was that the same fix should be applied to `sl6.x'.

Any comment by iscsi experts?

**Comment by Pansanel** [comment]
@jouvin : your previous comment:
@almumontiel Nice catch... and I'm wondering if it is not the cause for a problem we observe on only one of our server mounting an iscsi volume in fstab as iscsid, started by iscsi if needed, may be stopped by ncm-chkconfig. Strictly speaking, there is no reason for iscsid to be started by initd (or systemd) and so it was reasonable to have it in the UNWANTED_DAEMONS list but the startstop property should not be set for it. But your suggested modification should work (just if it has been marked as on manually, it will not be reset until OS_CORE_ISCSI_ENABLED is false).

Any comment by others with iscsi experience?

Also not that the same fix must probably done for sl6.x.

**Comment by jrha** [comment]
LGTM

**Pull request merged**
