### PR TITLE
rpms/quattor-development: add perl-File-Copy-Recursive

### PR DESCRIPTION
**Pull request by jouvin**

### CODE REVIEW

**Comment by jouvin** [comment]
Would help to have it in 15.2 but not essential... (required only for unit tests of build tools).

**Comment by stdweird** [comment]
@jouvin how is maven installed in this environment?

**Comment by jouvin** [comment]
It is not... In the past, with SPMA, it was a nightmare to install because of all the dependencies. May be this is better with YUM and should be revisited... At the same time, Maven was easy to install with the tarball... What the templates install are all the dependencies required to run the unit tests, `panc` and all the perl modules mainly.

**Comment by jouvin** [comment]
I just checked and Maven is still not part of a standard YUM repo (except may be JPackages that has been a source of pain in the past, due to conflicting packaging with SL for Java packages...)

**Comment by stdweird** [comment]
@jouvin i'm aware, that's why i was asking. i'm using https://github.com/quattor/release/blob/master/src/scripts/build_all_repos.sh#L122 in the `build_all_repos` script. it seems to work fine, but it is not a standard repository.

**Comment by jouvin** [comment]
Then, I suggest to update the Maven configuration provided by `cfg/standard/features/maven2`, currently JPackage based and optionally allow to configure it in `quattor-development` (for backward compatibility) (see https://github.com/quattor/template-library-standard/issues/46).

I suggest to merge this PR as it is as it fixes an issue with the recently added unit tests in maven tools.

**Pull request merged**
